### ISSUE TITLE
Mod Support

### ISSUE THREAD

**Issue by 8BitBoar** [ScottyThePilot/pz-buildplanner#1]
Hello! I came across your Reddit post with the link to your build planner and github  and have now been using it for, well, ever.

I wanted to know if you still take feature requests and to be more specific: mod integration requests. If so there is a recent mod called Hephas Occupations and Traits. Found Here: https://steamcommunity.com/sharedfiles/filedetails/?id=3256482412. Thank you for all your hard work regardless.

**Comment by ScottyThePilot** [comment]
Sure, if the author allows me to re-upload their icons here, I'll add support for it.

**Comment by ScottyThePilot** [comment]
Support for Hephas Occupations and Traits has been added.

**Comment by 8BitBoar** [comment]
Thank you very much! Pretty quick too!
